### ISSUE TITLE
undefined method `[]' for Data:Class

### ISSUE THREAD

**Issue by vasiliy0s** [joost/phony_rails#106]
When using in User model `phony_rails` validation with syntax:
```rb
class User < ActiveRecord::Base
   ...

    # other validations here
    validates :phone, if: :phone?, phony_plausible: true
    
    ...
end
```

In log I see additionally:
```
/home/vasiliy0s/.rvm/gems/ruby-2.2.1/gems/phony_rails-0.12.8/lib/phony_rails.rb:11: warning: toplevel constant Data referenced by ISO3166::Country::Data
```

Stack trace (partial)
```
phony_rails (0.12.8) lib/phony_rails.rb:11:in `country_number_for'
phony_rails (0.12.8) lib/validators/phony_validator.rb:32:in `country_number_from_country_code'
phony_rails (0.12.8) lib/validators/phony_validator.rb:24:in `country_number'
phony_rails (0.12.8) lib/validators/phony_validator.rb:14:in `validate_each'
activemodel (4.2.3) lib/active_model/validator.rb:151:in `block in validate'
activemodel (4.2.3) lib/active_model/validator.rb:148:in `each'
activemodel (4.2.3) lib/active_model/validator.rb:148:in `validate'
activesupport (4.2.3) lib/active_support/callbacks.rb:453:in `public_send'
activesupport (4.2.3) lib/active_support/callbacks.rb:453:in `block in make_lambda'
activesupport (4.2.3) lib/active_support/callbacks.rb:180:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:180:in `block in conditional'
activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `block in call'
activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `each'
activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
activemodel (4.2.3) lib/active_model/validations.rb:395:in `run_validations!'
activemodel (4.2.3) lib/active_model/validations/callbacks.rb:113:in `block in run_validations!'
activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
activemodel (4.2.3) lib/active_model/validations/callbacks.rb:113:in `run_validations!'
activemodel (4.2.3) lib/active_model/validations.rb:334:in `valid?'
activerecord (4.2.3) lib/active_record/validations.rb:58:in `valid?'
activerecord (4.2.3) lib/active_record/validations.rb:83:in `perform_validations'
activerecord (4.2.3) lib/active_record/validations.rb:37:in `save'
activerecord (4.2.3) lib/active_record/attribute_methods/dirty.rb:21:in `save'
activerecord (4.2.3) lib/active_record/transactions.rb:286:in `block (2 levels) in save'
activerecord (4.2.3) lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
activerecord (4.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
activerecord (4.2.3) lib/active_record/transactions.rb:220:in `transaction'
activerecord (4.2.3) lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
activerecord (4.2.3) lib/active_record/transactions.rb:286:in `block in save'
activerecord (4.2.3) lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
activerecord (4.2.3) lib/active_record/transactions.rb:285:in `save'
activerecord (4.2.3) lib/active_record/persistence.rb:252:in `block in update'
activerecord (4.2.3) lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
activerecord (4.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
activerecord (4.2.3) lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
activerecord (4.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
activerecord (4.2.3) lib/active_record/transactions.rb:220:in `transaction'
activerecord (4.2.3) lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
activerecord (4.2.3) lib/active_record/persistence.rb:250:in `update'
app/controllers/users_controller.rb:44:in `block in update'
actionpack (4.2.3) lib/action_controller/metal/mime_responds.rb:210:in `respond_to'
app/controllers/users_controller.rb:43:in `update'
```

**Comment by joost** [comment]
Please try v0.12.9 together with a recent countries gem. Let me know if that works.

**Comment by vasiliy0s** [comment]
Validatioin works (from issue descr), normalization (`phony_normalize`) works too, as I expect.
Thanks!
